spring:
  application:
    name: accounts-service
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  port: 8080